# Generated by Django 3.2.5 on 2021-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(default='#', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
