# Generated by Django 3.2.7 on 2021-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tracked',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(default='', upload_to='forum/images'),
        ),
    ]
