# Generated by Django 3.2.7 on 2021-09-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['tvotes', '-votes', '-date']},
        ),
    ]
