# Generated by Django 3.2.7 on 2021-09-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_notification_teacherprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
