# Generated by Django 3.2.7 on 2021-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
