# Generated by Django 3.2.7 on 2021-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='forum/images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='forum/images/'),
        ),
    ]
