# Generated by Django 3.2.7 on 2021-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_issue_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.TextField(default='(Not available)', max_length=200),
        ),
    ]
