# Generated by Django 3.2.7 on 2021-09-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_issue_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='', max_length=300),
        ),
    ]
