# Generated by Django 3.2.7 on 2021-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.TextField(default='', max_length=300),
        ),
    ]
