# Generated by Django 3.2.7 on 2021-09-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_teacherprofile_empno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='empno',
            new_name='rollno',
        ),
    ]
