# Generated by Django 3.2.7 on 2021-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100),
        ),
    ]
