# Generated by Django 3.2.7 on 2021-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rename_empno_teacherprofile_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('usernames', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('comments', models.JSONField(default=list)),
            ],
        ),
    ]
