# Generated by Django 3.2.7 on 2021-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='label',
            field=models.CharField(default='Untagged', max_length=100),
        ),
    ]
