# Generated by Django 3.2.7 on 2021-09-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_tags_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
