# Generated by Django 3.2.7 on 2021-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_issue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, upload_to='forum/images/users/%Y/%m/%d/'),
        ),
    ]
