# Generated by Django 3.2.7 on 2021-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='label',
            field=models.CharField(default='Untagged', max_length=100, unique=True),
        ),
    ]
