# Generated by Django 3.2.7 on 2021-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
