# Generated by Django 3.2.7 on 2021-09-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
