# Generated by Django 3.2.7 on 2021-09-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20210908_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
