# Generated by Django 3.2.7 on 2021-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='testing', max_length=255),
        ),
    ]
